### ISSUE TITLE
KRUN should be used in payload tests

### ISSUE THREAD

**Issue by msterin** [kontainapp/km#1098]
We run payload tests in regular docker, should use it KRUN to validate all the changes

//CC @gnode1 @paulpopelka

**Comment by paulpopelka** [comment]
The description does not state clearly that this issue refers to testing what is in the payloads directory.
I'm just stating this to clarify what is to be tested.

**Comment by paulpopelka** [comment]
Currently we test the containers made for each of the payloads using the validate-runenv-image make target.
That target runs kontainapp/demo-runenv-${COMPONENT} container where component is what is built in each of the payload directories. 
The change that fixed this is 947175fe8fd28da83bd112a58478d0da3ef8147a,
The review for it was: https://github.com/kontainapp/km/pull/1322
