### ISSUE TITLE
KM exec() failures show in Node as "  errno: 'Unknown system error -8',

### ISSUE THREAD

**Issue by msterin** [kontainapp/km#1134]
when Node can't exec CLI e.g. (system("ls"(), it returns 'Unknown system error -8'

Not sure why  node misinterpreting ENOEXEC. We seem to do fine (I've added a test and we do return ENOEXEC properly) 

related to #1112

**Comment by gnode1** [comment]
Caused by our simplified shell emulation. Disappears with the busybox shell
