### ISSUE TITLE
KKM:  should we FULLY separate KKM from KM repo ? 

### ISSUE THREAD

**Issue by msterin** [kontainapp/km#1147]
up for discussion:  should we FULLY separate KKM from KM repo ? 

it means 
- KKM repo just uses headers from KM release 
- KKM has it's own  release (source + kkm.run) based on GitHub Releases mechanism 
- pre-packaged KM Vagrant box/etc pick iKKM up from KKM releases. KM release does not have KKM 
- KM still kicks off kkm CI so KM changes are validated vs KKM

**Comment by gnode1** [comment]
KKM is completely independent of KM at compile time. At run time KM and KKM and codependent.
And KKM is a separate repo.
