### ISSUE TITLE
k8s: kontain RuntimeClass support for containerd

### ISSUE THREAD

**Issue by johnmuth81** [kontainapp/km#1326]
Add support for the kontain RuntimeClass to `containerd`.

Will need to write a containerd shim and config.

See https://github.com/containerd/containerd/tree/main/runtime/v2/example for containerd shim example.

See https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/scripts/kata-deploy.sh for installation script ideas.

**Comment by gnode1** [comment]
This should also enable us to install our runtime on managed k8s clusters such as AKS.

**Comment by johnmuth81** [comment]
The shim is done and in master
