### ISSUE TITLE
Document EKS integration with Kontain

### ISSUE THREAD

**Issue by johnmuth81** [kontainapp/km#1392]
Document how Kontain runtime integrates with AWS Elastic Kubernetes Service

It looks like it is possible to add custom worker nodes to EKS clusters. See:

https://aws.amazon.com/premiumsupport/knowledge-center/eks-worker-nodes-cluster/
This gives the steps needed to bootstrap a kubernetes worker node.

https://github.com/kelseyhightower/kubernetes-the-hard-way

**Comment by johnmuth81** [comment]
It looks like it is possible to add custom worker nodes to EKS clusters. See:
- https://aws.amazon.com/premiumsupport/knowledge-center/eks-worker-nodes-cluster/

This gives the steps needed to bootstrap a kubernetes worker node.
- https://github.com/kelseyhightower/kubernetes-the-hard-way

**Comment by ez-leka** [comment]
There is now a way to build EKS Kontain pre-configured AMI.

script cloud/aws/amazon-eks-ami/scripts/make-cluster.sh creates kontain-enabled EKS cluster
script cloud/aws/amazon-eks-ami/test-cluster.sh  delays runctimeClas and test  application. 

Let me know if you. need more info or if you prefer that I write the doc, let me know where to put it (and maybe point me to an example).

**Comment by smijar** [comment]
So we might need to update the guide here (line 107) with steps for an end user to create an AMI-based EKS cluster:
https://github.com/kontainapp/guide/blob/main/getting_started/kubenetes.md?plain=1#L107
