### ISSUE TITLE
Combined yaml for installing Kontain including runtime class, configmap, lib, runtime deploy (eventually Helm chart)

### ISSUE THREAD

**Issue by smijar** [kontainapp/km#1395]
Just a thought on this when I started documenting the install and wanted to see what you think?  It might be easier for an external audience, if we can integrate the 4 files into 1 yaml install file for each runtime.

"kontain-deploy-containerd.yml" that includes:

runtime-class.yaml
cm-install-lib.yaml
cm-containerd-install.yaml
kontain-deploy.yaml

or

"kontain-deploy-crio.yml" that includes:

runtime-class.yaml
cm-install-lib.yaml
cm-crio-install.yaml
kontain-deploy.yaml

Let me know what you think and I can add this file to the cloud/deploy/k8s folder for sake of documentation, and not CI.

**Comment by smijar** [comment]
We will use the shell script to install Kontain YAMLs inside kubernetes and the script will determine which runtime is being used by doing $ kubectl get nodes -o w and then using that to determine the yaml bundle to be used for that runtime.

**Comment by ez-leka** [comment]
implemented in kontain-deploy repo
