### ISSUE TITLE
Integrate k3s Daemonset install with kustomize and install.sh for various K8s cluster types

### ISSUE THREAD

**Issue by smijar** [kontainapp/km#1420]
I was able to use Kontain successfully in a vagrant based K3s cluster, after some tweaks to install script to take K3S and containerd config.toml differences

I have included the changes in a branch that will need to be merged with main branch in a way that we can support Minikube, K3s, AKS and other distributions.

The branch changes are in this folder:
[https://github.com/kontainapp/km/tree/sm/k3s/cloud/k8s/deploy](https://github.com/kontainapp/km/tree/sm/k3s/cloud/k8s/deploy
)

I made tweaks to:
cm-install-lib.yaml script
cm-containerd-install.yaml script
deploy/kontain-deploy.yaml contents

We will need to work with the kustomize template config for various cluster type deployments that we support:
- Minikube
- K3s
- AKS

We will also need to integrate this with the install script so that the right kustomize template is invoked depending on the target cluster type that we are deploying to.

**Comment by ez-leka** [comment]
This has been addressed by kontain-deploy repo. Supports Minikube, AKS, EKS, GKE , K3s with single script
