### ISSUE TITLE
Use static KRUN binary in kontain.tar.gz (big release)

### ISSUE THREAD

**Issue by johnmuth81** [kontainapp/km#1426]
We currently include two tar files as part of our release:
- `kontain.tar.gz` - Full release with examples, payloads, etc. Intended for desktop users
- `kontain_bin.tar.gz` - Minimal binary release. Initially intended for k8s Nodes.

The binary release `kontain_bin.tar.gz` includes a static linked KRUN. The full release `kontain.tar.gz` includes dynamic linked KRUN. The full release should include static KRUN too.

**Comment by gnode1** [comment]
Should be covered by https://github.com/kontainapp/km/pull/1557
