### ISSUE TITLE
CI pipeline failing in `km-tests`: make -C tests test-withk8s TEST_JOBS=4

### ISSUE THREAD

**Issue by johnmuth81** [kontainapp/km#1463]
Use this issue to maintain notes on the problem.

### Initial Analysis
It looks like `/dev/kvm` isn't available for some reason. This test uses the old `kontaind` mechanism, so a DaemonSet 
running `quay.io/kubevirt/device-plugin-kvm:latest` makes the KVM device available to pods that ask for it.
**It would be interesting to see what the logs for the DaemonSet have to _say. **
### Background
The command executing is: 
```
TEST_IMAGE='kontainkubecr.azurecr.io/test-km-fedora:ci-1002', TEST_COMMAND='/home/appuser/km/tests/run_bats_tests.sh --match= --usevirt=  --jobs=4 --km=/opt/kontain/bin/km'
```
The error message is:
```
error: timed out waiting for the condition on pods/test-km-fedora-ci-1002
k8s-run-tests.sh: Failed to launch pod. Timeout=5m
```
Here are the pod events :
```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  5m1s                  default-scheduler  0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
  Warning  FailedScheduling  3m40s (x1 over 5m1s)  default-scheduler  0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
```

**Comment by gnode1** [comment]
Obsoleted by the new CI using on-demand self hosted runner. And we use different way to run thing in k8s
