### ISSUE TITLE
DevOps Automation for ECS cluster install with AMI

### ISSUE THREAD

**Issue by smijar** [kontainapp/km#1484]
We need a repeatable way to setup an ECS cluster for testing and dev purposes.  Will be trying out Terraform for this.

**Comment by gnode1** [comment]
For now we'll creat an internal doc in km repo, documenting how to instantiate kontain enabled ECS cluster. This is the same process that is used in the ECS AMI test

**Comment by smijar** [comment]
This is done yes.  I will close it out.
