### ISSUE TITLE
add 'default-runtime' clause to /etc/docker/daemon.json only for ECS since docker and k8s support runtime clause

### ISSUE THREAD

**Issue by smijar** [kontainapp/km#1509]
we need to support 'krun' (krun-label-trigger) as default runtime in ECS since ECS does not support a 'runtime' clause.  This change should only be applied to ECS nodes.

```shell
$ cat /etc/docker/daemon.json
{
  "default-runtime":"krun",
  "runtimes": {
    "krun": {
      "path": "/opt/kontain/bin/krun"
    }
  }
}
```

**Comment by gnode1** [comment]
I'm not sure what is requested here. We build our own AMI for ECS, we put krun-label-trigger as runtime, and because if the hack in it both standard and ours will run. What is missing?
