### ISSUE TITLE
Update ECS AMI

### ISSUE THREAD

**Issue by johnmuth81** [kontainapp/km#1633]
The current Amazon ECS AMI we captured is from January. We might want to look at updating it.

**Comment by gnode1** [comment]
Our AMIs are a bit of a mess. There are four zones - us-{east,west}-{1,2}. Each has some AMIs with a bit of a mix in the names. We need to clean these up - remove the cruft and make sure we have the right ones. 
However, there is one in us-west-1 - [ami-0f3072553646bdaf6](https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1#ImageDetails:imageId=ami-0f3072553646bdaf6) - which is the right one, build in May, same as the last release.

There are three other issues https://github.com/kontainapp/km/issues/1580, https://github.com/kontainapp/km/issues/1579, https://github.com/kontainapp/km/issues/1578 that are related.

The AMIs on AWS seem to be specific to region. We should either find out a way to make out AMIs visible in several regions, or have a duplication step in the pipeline.
