### ISSUE TITLE
snapshot of subordinate process is causing issues.

### ISSUE THREAD

**Issue by sv641** [kontainapp/km#1662]
currently only the first process in the container can be snapshoted and namedpipe conflicts with second process.

19:01:52.405368 km_mgt_init          123  km      bind failure: /tmp/kmmgmt.pipe-1: Address already in use

**Comment by gnode1** [comment]
https://github.com/kontainapp/km/pull/1683 addresses the management pipe naming, allowing snapshot of any process in a kontainer.
