### ISSUE TITLE
Own the kvm device plugin in kontaind, and add kkm support

### ISSUE THREAD

**Issue by yihuaf** [kontainapp/km#511]
We currently use `quay.io/kubevirt/device-plugin-kvm` from `https://github.com/kubevirt/kubernetes-device-plugins`. Unfortunately the project is no longer maintained. There is also a bug where it doesn't accurately account the number of kvm devices. It has to do with the work around where k8s requires device plugin to give a concrete number of device, whereas kvm can be use infinitely.

Decision: fork or include our own implementation of the kvm device plugin. Try to resolve is bug as well.

msterin> also, piggybacking on this one to add "we also need to support /dev/kkm"

**Comment by johnmuth81** [comment]
We've deprecated `kontaind`. Closing.
