### ISSUE TITLE
Snapshots: outstanding timers  / eventfd/ IO in flight 

### ISSUE THREAD

**Issue by msterin** [kontainapp/km#936]

**Comment by paulpopelka** [comment]
event fd's and epoll fd's are handled now.  There are still conditions for them that can't be handled but the snapshot is failed in that case and the payload will continue to run so the snapshot can be reattempted.

Data buffered in pipes and socketpairs where both ends are in the process being snapshotted is saved in the snapshot and is recovered.  pipes and socketpairs between 2 processes aren't handled.

The presence of active timers will still cause a snapshot request to fail but the process continues to run.
If we need to handle snapshotting active timers that can be addressed by a future issue.

I'm going to close this.
