### ISSUE TITLE
snapshots: Pipe, socketpair contents. 

### ISSUE THREAD

**Issue by msterin** [kontainapp/km#937]
We do not save or restore any on-the-wire data in pipes or socket pairs. This is important because ‘loopback’ pipes are used in epoll based code like node

**Comment by paulpopelka** [comment]
This is fixed by 
1e07fab1 Change snapshot to handle data buffered in half open pipes and socketpairs. (#1676)
7ec6509c Add support for snapshoting data buffered in a socketpair (#1670)
